version: "3.7"
services:
  
  haproxy:
    image: haproxy:alpine
    volumes:
      - ./haproxy/:/usr/local/etc/haproxy/
    depends_on:
      - inspircd1
    ports:
      - "6667:6667"
      - "7000"
    networks:
      - backend

  inspircd1:
    image: inspircd/inspircd-docker
    volumes:
      - ./server1/conf/:/inspircd/conf/
    environment:
      INSP_NET_NAME: inspircd1
      INSP_SERVER_NAME: inspircd1.local
      INSP_NET_SUFFIX: .local

      INSP_LINK1_NAME: inspircd2
      INSP_LINK1_IPADDR: inspircd2
      INSP_LINK1_SENDPASS: password
      INSP_LINK1_RECVPASS: password
      INSP_LINK1_TLS_ON: "no"
    ports:
      - "6667" #client
    #  - "6697" #client
      - "7000" #server
    #  - "7001" #server
    networks:
      - backend
       # aliases:
       #   - inspircd1.local

  inspircd2:
    image: inspircd/inspircd-docker
    volumes:
      - ./server1/conf/:/inspircd/conf/
    environment:
      INSP_NET_NAME: inspircd2
      INSP_SERVER_NAME: inspircd2.local
      INSP_NET_SUFFIX: .local
      
      INSP_LINK1_NAME: inspircd1
      INSP_LINK1_IPADDR: inspircd1
      INSP_LINK1_SENDPASS: password
      INSP_LINK1_RECVPASS: password
      INSP_LINK1_TLS_ON: "no"
    ports:
      - "6667"
  #    - "6697"
      - "7000"
  #    - "7001"
    networks:
      - backend

  


  #nginx: 
  #  image: 'bitnami/nginx'
  #  volumes:
  #    - ./nginx/:/etc/nginx
  #  ports:
  #    - '6667:6667'
  #    - '6697:6697'
  #  links:
  #    - inspircd1
  #    - inspircd2
  #  networks:
  #    - backend

networks:
  backend:

