version: "3.7"
services:
  
  haproxy:
    image: haproxy:alpine
    volumes:
      - ./haproxy/:/usr/local/etc/haproxy/
    depends_on:
      - inspircd1
    ports:
      - "6667:6667"
    networks:
      - backend

  inspircd1:
    image: inspircd/inspircd-docker
    volumes:
      - ./server1/conf/:/inspircd/conf/
    environment:
      INSP_NET_NAME: inspircd1
      INSP_SERVER_NAME: inspircd1.local
      INSP_NET_SUFFIX: .local

      INSP_LINK1_NAME: inspircd2.local
      INSP_LINK1_IPADDR: inspircd2
      INSP_LINK1_SENDPASS: password
      INSP_LINK1_RECVPASS: password
      INSP_LINK1_TLS_ON: "no"
      INSP_LINK1_ALLOWMASK: 10.0.0.0/16
      
      INSP_LINK2_NAME: anope.local
      INSP_LINK2_IPADDR: anope
      INSP_LINK2_SENDPASS: anope
      INSP_LINK2_RECVPASS: anope
      INSP_LINK2_PORT: 7000
      INSP_LINK2_TLS_ON: "no"
      INSP_LINK2_ALLOWMASK: 10.0.0.0/16
    ports:
      - "6667" #client
      - "7000" #server
      - "7001"
    networks:
      - backend

  inspircd2:
    image: inspircd/inspircd-docker
    volumes:
      - ./server2/conf/:/inspircd/conf/
    environment:
      INSP_NET_NAME: inspircd2
      INSP_SERVER_NAME: inspircd2.local
      INSP_NET_SUFFIX: .local
      
      INSP_LINK2_NAME: inspircd1.local
      INSP_LINK2_IPADDR: inspircd1
      INSP_LINK2_SENDPASS: password
      INSP_LINK2_RECVPASS: password
      INSP_LINK2_TLS_ON: "no"
      INSP_LINK2_ALLOWMASK: 10.0.0.0/16
    ports:
      - "6667"
      - "7000"
    networks:
      - backend

  anope:
    image: anope/anope
    environment:
      ANOPE_SERVICES_NAME: anope.local
      ANOPE_SERVICES_VHOST: anope
      ANOPE_UPLINK_IP: inspircd1
      ANOPE_UPLINK_PORT: 7000
      ANOPE_UPLINK_PASSWORD: anope
      
      #ANOPE_SQL_ENGINE: mysql
      #ANOPE_MYSQL_PASSWORD: anope
    ports:
      - "7000"
    depends_on:
      - inspircd1
    networks:
      - backend
      
  #database:
  #  image: mysql
  #  restart: always
  #  environment:
  #    MYSQL_USER: anope
  #    MYSQL_ROOT_PASSWORD: root
  #    MYSQL_PASSWORD: anope
  #    MYSQL_DATABASE: anope
  #  networks:
  #    - backend

networks:
  backend:

